/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cueva;
import java.awt.Image;
import javax.swing.*;

/**
 *
 * @author toniborras
 */
public class View extends javax.swing.JFrame {

    
    /**
     * Creates new form View
     */
    public View(Main p) {
        initComponents();
        Tablero t= new Tablero();
        this.jPanel3.add(t);
        this.mostrar();
    }
    
     public void mostrar() {
        this.pack();

        setLocationRelativeTo(null);
        setTitle("Ascensor");
        //setSize(769,610);

        ImageIcon wallpaper = new ImageIcon("src/img/cerrado.png");
//        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(this.Ascensor.getWidth(), this.Ascensor.getHeight(), Image.SCALE_DEFAULT));
//        Icon icono1 = new ImageIcon(rojo.getImage().getScaledInstance(this.bajPrimero.getWidth(), this.bajPrimero.getHeight(), Image.SCALE_DEFAULT));
//        Icon icono2 = new ImageIcon(rojo.getImage().getScaledInstance(this.bajSegundo.getWidth(), this.bajSegundo.getHeight(), Image.SCALE_DEFAULT));
//        Icon icono3 = new ImageIcon(rojo.getImage().getScaledInstance(this.bajtercero.getWidth(), this.bajtercero.getHeight(), Image.SCALE_DEFAULT));
//        Icon icono4 = new ImageIcon(rojo.getImage().getScaledInstance(this.bajCuarto.getWidth(), this.bajCuarto.getHeight(), Image.SCALE_DEFAULT));
//        Icon icono5 = new ImageIcon(rojo.getImage().getScaledInstance(this.subPrimero.getWidth(), this.subPrimero.getHeight(), Image.SCALE_DEFAULT));
//        Icon icono6 = new ImageIcon(rojo.getImage().getScaledInstance(this.subSegundo.getWidth(), this.subSegundo.getHeight(), Image.SCALE_DEFAULT));
//        Icon icono7 = new ImageIcon(rojo.getImage().getScaledInstance(this.subTercero.getWidth(), this.subTercero.getHeight(), Image.SCALE_DEFAULT));
//        Icon icono8 = new ImageIcon(rojo.getImage().getScaledInstance(this.subBajo.getWidth(), this.subBajo.getHeight(), Image.SCALE_DEFAULT));
//
//        Icon icono11 = new ImageIcon(rojo.getImage().getScaledInstance(this.jLabel2.getWidth(), this.jLabel2.getHeight(), Image.SCALE_DEFAULT));
//        Icon icono22 = new ImageIcon(rojo.getImage().getScaledInstance(this.jLabel3.getWidth(), this.jLabel3.getHeight(), Image.SCALE_DEFAULT));
//        Icon icono33 = new ImageIcon(rojo.getImage().getScaledInstance(this.jLabel4.getWidth(), this.jLabel4.getHeight(), Image.SCALE_DEFAULT));
//        Icon icono44 = new ImageIcon(rojo.getImage().getScaledInstance(this.jLabel5.getWidth(), this.jLabel5.getHeight(), Image.SCALE_DEFAULT));
//        Icon icono55 = new ImageIcon(rojo.getImage().getScaledInstance(this.jLabel6.getWidth(), this.jLabel6.getHeight(), Image.SCALE_DEFAULT));

//        this.Ascensor.setIcon(icono);
//        this.subBajo.setIcon(icono8);
//        this.bajPrimero.setIcon(icono1);
//        this.bajSegundo.setIcon(icono2);
//        this.bajtercero.setIcon(icono3);
//        this.bajCuarto.setIcon(icono4);
//        this.subPrimero.setIcon(icono5);
//        this.subSegundo.setIcon(icono6);
//        this.subTercero.setIcon(icono7);

//        this.jLabel2.setIcon(icono11);
//        this.jLabel3.setIcon(icono22);
//        this.jLabel4.setIcon(icono33);
//        this.jLabel5.setIcon(icono44);
//        this.jLabel6.setIcon(icono55);
        try {
            Thread.sleep(500);
        } catch (Exception e) {
        }

        this.setResizable(false);
        this.revalidate();
        //this.repaint();
        this.setVisible(true);

//        animacion(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(100, 100, 100));

        jButton1.setText("Monstuos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Tesoros");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jButton3.setText("Fosos");

        jLabel3.setText("jLabel3");

        jButton4.setText("Iniciar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton4)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton4)
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addComponent(jButton1)
                .addGap(51, 51, 51)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGap(65, 65, 65)
                .addComponent(jButton3)
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 600));

        jPanel3.setBackground(new java.awt.Color(253, 253, 150));
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
